### ISSUE TITLE
Crate name on Crates.io

### ISSUE THREAD

**Issue by tidwall** [importcjj/rust-ajson#2]
Hi, nice work on porting gjson from Go to Rust. 

I'm the creator and maintainer of the [official gjson project](https://github.com/tidwall/gjson) and the [gjson specification](https://github.com/tidwall/gjson/blob/master/SYNTAX.md). 

I noticed that you chose to use the crate name `gjson` in crates.io. It so happens that the official Rust version of gjson is currently in development.

I'm asking you if you could assign the ownership of the name to me as I believe the Rust community would benefit from having the `gjson` crate name point to the official project.
https://crates.io/policies#package-ownership

Opening this issue to raise the concern as early as possible, because changing the crate name is easier at the early stage of the project.

**Comment by importcjj** [comment]
What a coincidence, I did the rust version of gjson by myself because of the good syntax of gjson. Now that you've asked, I'll change the name of the project, but I might need some time. By the way, how do you know about this project?

**Comment by tidwall** [comment]
Great. Thanks for agreeing. 

The sooner the ownership can be changed the better, as I would like to publish soon. 

The instructions are simple. From the crates.io [policy page](https://crates.io/policies#package-ownership) state:

> If someone wants to take over a package, and the previous owner agrees, the existing maintainer can add them as an owner, and the new maintainer can remove them. If necessary, the team may reach out to inactive maintainers and help mediate the process of ownership transfer.

So you should be able to add me `tidwall` as an owner of your crate.

Here's the command to add me as an owner.

```
cargo owner --add tidwall
```

https://doc.rust-lang.org/cargo/reference/publishing.html#managing-a-cratesio-based-crate

> By the way, how do you know about this project?

Your project popped up on my Github timeline and also on the crates.io homepage.

**Comment by tidwall** [comment]
I tried to do a `cargo publish` from my side, but I'm still getting this error:

> error: api errors (status 200 OK): this crate exists but you don't seem to be an owner. 

This command still needs to be run from your side as a last step:

```
cargo owner --add tidwall -- gjson
```

Thanks

**Comment by importcjj** [comment]
I'm sorry, but I have already done, and got "An invite has been sent to tidwall".

**Comment by tidwall** [comment]
Everything looks good. Thank you.
