### ISSUE TITLE
bracket in array value

### ISSUE THREAD

**Issue by kuerant** [importcjj/rust-ajson#6]
Hi,

There is a bug when a bracket sits in array's value.

#[test]
fn test_bracket_in_array() {
    let json = r##"{
        "children": ["Sara","Alex]","Jack"],
    "##;
    let r = parse(json).unwrap();
    assert_eq!(r.get("children.#").unwrap().to_i64(), 3); 
    assert_eq!(r.get("children").unwrap().to_vec(), vec!["Sara", "Alex]", "Jack"]);
    assert_eq!(r.get("children.1").unwrap(), "Alex]");
    assert_eq!(r.get("child*.2").unwrap(), "Jack");
    assert_eq!(r.get("c?ildren.0").unwrap(), "Sara");
}

---- test_bracket_in_array stdout ----
thread 'test_bracket_in_array' panicked at 'assertion failed: `(left == right)`
  left: `["Sara", "Alex]"]`,
 right: `["Sara", "Alex]", "Jack"]`', tests/test_ajson.rs:590:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by importcjj** [comment]
Sorry for late, I didn't receive the notification. I will fix this problem.
